### PR TITLE
Add manifest files to include all test data in sdists

### PR DESCRIPTION
**Pull request by cdce8p**
Replaces #43

### CODE REVIEW

**Review by meeuw — APPROVED** [review]
Works for me!

**Review by youknowone — APPROVED** [review]
Thanks, you are a packaging master

**Comment by youknowone** [comment]
@meeuw Do you also need a new release to pypi? If it id related to fedora package, it does not look necessary though.

**Comment by meeuw** [comment]
Thanks a lot you both, please release a new version on PyPI. That's what used for building packages.

**Comment by youknowone** [comment]
Is the build tool depending on pypi? Since fedora packafing usually have its own local patches for many projects, I expected they are not coupled much

**Comment by meeuw** [comment]
My bug report for adding mailcap in Fedora can be found here:
https://bugzilla.redhat.com/show_bug.cgi?id=2328464

This is the proposed spec file:
https://copr-dist-git.fedorainfracloud.org/cgit/meeuw/alot/python-standard-mailcap.git/plain/python-standard-mailcap.spec?h=f41

It's quite common to use the `%{pypi_source}` macro to download the tarball from PyPI but it can be anything (also github).

The sdist on PyPI would be different to the archives generated for GitHub tags.

I think it's best to release to PyPI, but if you have strong objections or like to delay it a bit I'm also fine with that.

**Pull request merged**
